version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./data/highscores.json:/app/highscores.json
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - HOST=0.0.0.0
    command: gunicorn --bind ${HOST}:5000 --workers 2 app:app
    restart: unless-stopped
