apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mathpuzzle-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
    - 2a01-4f8-1c18-a7--1.sslip.io
    secretName: mathpuzzle-tls
  rules:
  - host: 2a01-4f8-1c18-a7--1.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mathpuzzle-service
            port:
              number: 80
