apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathpuzzle-web
spec:
  template:
    spec:
      containers:
      - name: web
        env:
        - name: ALLOWED_ORIGINS
          value: "https://sharphuman.app"
