apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mathpuzzle-ingress
  namespace: mathpuzzle
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # UNCOMMENT the line below for Production (forces HTTPS)
    # COMMENT the line below for Local Testing (avoids 403 errors)
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
    - 127.0.0.1.sslip.io # TODO: Replace with your actual VPS IP (e.g. 1.2.3.4.sslip.io) or Domain
    secretName: mathpuzzle-tls
  rules:
  - host: 127.0.0.1.sslip.io # TODO: Replace with your actual VPS IP or Domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mathpuzzle-service
            port:
              number: 80
